import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import abi from "../abi"
import {useWriteContract} from 'wagmi';
import styles from '../styles/Home.module.css';
import { useAccount } from 'wagmi'
const Home: NextPage = () => {
  const {writeContract} = useWriteContract()
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
       `` <link href="/favicon.ico" rel="icon" />
        {/* CSS for parallax effect */}
        <style>
          {`
            body, html {
              height: 100%;
              margin: 0;
            }
            .parallax {
              /* The image used */
              background-image: url('your-background-image.jpg');
              /* Full height */
              height: 100%;
              /* Create the parallax scrolling effect */
              background-attachment: fixed;
              background-position: center;
              background-repeat: no-repeat;
              background-size: cover;
            }
          `}
        </style>
      </Head>

      {/* Add parallax class to main */}
      <main className={`${styles.main} parallax`}>
        <ConnectButton />

        <h1 className={styles.title}>
          Welcome to C-VIM
        </h1>
        <button onClick={()=>writeContract({ 
      address: '0xba18fF7530b23F2137EdbCAdfBDB78a015CAE018', 
      abi, 
      functionName: 'Transfer',
      args: ['0xd3bea327fFe7A959cD414De6081702f3bC9667ab',1], 
    }) } className=''> Transfer </button>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};
const handleTransaction = async () => {
  const amount = document.getElementById("amountInput").value;
  // ... other user input if needed

  try {
    const tx = await rainbowKit.contracts.executeFunction(contractAddress, "yourTransactionFunction", [amount]);
    console.log("Transaction submitted:", tx.hash);
  } catch (error) {
    console.error("Transaction failed:", error);
  }
};

export default Home;

